name: Build and Push to ECR

on:
  workflow_dispatch:

jobs:
  build_and_push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 609324725328.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: 609324725328.dkr.ecr.us-east-2.amazonaws.com
          ECR_REPOSITORY: maven_mlops_test
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker buildx build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --load .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG